#!/bin/bash
# Credits for: Krzysieqq (https://github.com/krzysieqq/DUNP)
set -e


case $1 in
  help|-h|--help)
    echo "Usage (params with '*' are optional):"
    echo "Global commands:"
    echo "./run build                     Built the whole project and run"
    echo "./run start                     Run the whole monorepo"
    echo ""

    ./backend/scripts/run help
    echo ""
    ./frontend/scripts/run help
  ;;
  bo)
    chmod +x frontend/scripts/run
    ./backend/scripts/run $2
    exit
  ;;
  build)
    sudo docker compose up --build
    exit
  ;;
  start)
    sudo docker compose up
    exit
  ;;
  fo)
    chmod +x frontend/scripts/run
    ./frontend/scripts/run $2
    exit
  ;;
  *)
  exit
  ;;
esac
